//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DsiMq_IF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=DISPC_HY;persist security info=True; Integr" +
            "ated Security=SSPI;")]
        public string connectionString {
            get {
                return ((string)(this["connectionString"]));
            }
            set {
                this["connectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomerCode {
            get {
                return ((string)(this["CustomerCode"]));
            }
            set {
                this["CustomerCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JQI62fq8EqUFFgwIfAqC97MIyoM6bkvyqGL7ASgn60N72dYuYR8WJQxd7Yr9TxiLMSnTB7ObTCQFDVOoP" +
            "1PTY8hbiZQCr9zsXI52ZMN5jpG4JeMK+WE2s0+nFJJE1CT9WoMSi/ikESF7Ma8R5Uh/eFQEQ/uUwy+OA" +
            "0ZpWsKN4pw=")]
        public string Key {
            get {
                return ((string)(this["Key"]));
            }
            set {
                this["Key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yj4moYLtvqBIMWabgwIzU9kKn4yJH0hfzutHXbUG8YWlwKsjgwYsb7+A7gYKwXeAtb/c/v21bt2Y1k7OI" +
            "ZOaFtusE4yZ0zw/FWObTH0jP9wD9wBj9SXonwtXOJWsHTXije9RL5b8Zml0Wpi1CLoou7SWmGF14nUl9" +
            "K41UgyRjbI=")]
        public string KeyName {
            get {
                return ((string)(this["KeyName"]));
            }
            set {
                this["KeyName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B76pWa4k+tHio4+EzwtF0YFxp3cJLQuIDCBBIA7HjVd7+JpFvUcpqjCsCCJ/VWk6LS+eoFf3anC6FZhqx" +
            "nZ6BrxZEYYcC2Dmb6sYqWI5hOpeMetlU/r3nDIqlS0qLILSeoBvI7isgWeikr+5XBZTrPlqPUH0J7pGl" +
            "JMmGEzB4/s=")]
        public string NameSpace {
            get {
                return ((string)(this["NameSpace"]));
            }
            set {
                this["NameSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ZNCvS8RaEbcxEMjEJKDhrBYnxUwRn1fyo15/kMtRuBU688HYMJY/iT8I9QuCXG4I7kINXEtMCQy1W0uHv" +
            "r6/FGkhjWH6+SRrM6ajMCLWXXkb78u8+a9ulCGT2g25kZ19IEfhnEPcfM8ckhJI/ooqnJW1/EcfMBCWF" +
            "Dca6zaw6/I=")]
        public string ServerUrl {
            get {
                return ((string)(this["ServerUrl"]));
            }
            set {
                this["ServerUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5Q1pqGxuVMGh6TzHwNJoA8wY6wyu42F1B1O3l1FA9G6ZrSLoRIsYmjaR8VJ4wubOu0Au22OOIxqmm0ok0" +
            "SYP/yt7AVPFRZT/zTTdWNVIPYX4pbUYEkGMVxuu2WEFOnTGZkv6BOKKiZnDE/wctMvbLFAJvIEsGIiUi" +
            "dKM0N15Dnc=")]
        public string topicName {
            get {
                return ((string)(this["topicName"]));
            }
            set {
                this["topicName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("u1rJf4KS37pbbljuUhcD2/F9nSu13ZWkf0DTdnqysqORT0AgIaN5b0EEHYFdZa3pRRmFz3C46C77IX+t3" +
            "svQ4BfyBDyqi5VO42U1btV4xiBQj8GdNO40rwP+3S3ePYEwu8e7qWYt0Eyw1HkZ/tWSfPRIOyX77Cmxg" +
            "tMy/BHCcF4=")]
        public string standardKey {
            get {
                return ((string)(this["standardKey"]));
            }
            set {
                this["standardKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sLd97JvLU1ZwtT0Fqbtd+CLeurFt469f2z3iAaX0ytLyb/jdnl0BR467EFW9EINpVaa2aRxuvFicQd1nu" +
            "9fpTiay43FFsaxQ9lT8wYCUBWGBVwvcpmPUQuBMEjFKE0QFKxF+n6GvAJHX10tRQ8NUUHu7IogjHkdg6" +
            "2Vr4GO7ATc=")]
        public string measureKey {
            get {
                return ((string)(this["measureKey"]));
            }
            set {
                this["measureKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GjQA72YZL9Ltx3a+/Vb6BNhvtt1CWNdNahKnNhO//sZvh+Xnyj19YjnbUvNIGHgie3AtLqW2UXcAdLSbl" +
            "sSSd49ZXojla8lcdsEs7+RLd2/96lKgLFIx6If0HEF7QCLCjUevl91cDcknSZNBuhRJh8qH99dBT4jMX" +
            "KZrXcJxwjI=")]
        public string StatKey {
            get {
                return ((string)(this["StatKey"]));
            }
            set {
                this["StatKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CqW7abfewIFniuGFKfHhf31zNVDMHrABufMPBy6GO7jY4wSDvp4VUyGkvQoL6cxofyEr12MZh7AIrMRjd" +
            "zSVSLY0tHuly7EnIbvXYO2DcLhfwJZWeMORV876CfhbU3oIXsRu/bMzl5ZqaWANGZ62sZZ/ZWCzNoh/u" +
            "aNcyxcAD7A=")]
        public string BadKey {
            get {
                return ((string)(this["BadKey"]));
            }
            set {
                this["BadKey"] = value;
            }
        }
    }
}
